/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // But you can create a sidebar manually
  techPost: [
    {
      type: 'category',
      label: '2023',
      link: {
        type: 'generated-index',
        description: "2023 年發布之各種技術文"
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'techPost/2023',
        }
      ],
    },
    {
      type: 'category',
      label: '2022',
      link: {
        type: 'generated-index',
        description: "2022 年發布之各種技術文"
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'techPost/2022',
        }
      ],
    },
    {
      type: 'category',
      label: '2021',
      link: {
        type: 'generated-index',
        description: "2021 年發布之各種技術文"
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'techPost/2021',
        }
      ],
    },
    {
      type: 'category',
      label: '2020',
      link: {
        type: 'generated-index',
        description: "2020 年發布之各種技術文"
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'techPost/2020',
        }
      ],
    },
    {
      type: 'category',
      label: '2019',
      link: {
        type: 'generated-index',
        description: "2019 年發布之各種技術文"
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'techPost/2019',
        }
      ],
    },
    {
      type: 'category',
      label: '2018',
      link: {
        type: 'generated-index',
        description: "2018 年發布之各種技術文"
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'techPost/2018',
        }
      ],
    },
    {
      type: 'category',
      label: '2017',
      link: {
        type: 'generated-index',
        description: "2017 年發布之各種技術文"
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'techPost/2017',
        }
      ],
    },
    {
      type: 'category',
      label: '2016',
      link: {
        type: 'generated-index',
        description: "2016 年發布之各種技術文"
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'techPost/2016',
        }
      ],
    },
    {
      type: 'category',
      label: '2015',
      link: {
        type: 'generated-index',
        description: "2015 年發布之各種技術文"
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'techPost/2015',
        }
      ],
    },
    {
      type: 'category',
      label: '2014',
      link: {
        type: 'generated-index',
        description: "2014 年發布之各種技術文"
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'techPost/2014',
        }
      ],
    },
    {
      type: 'category',
      label: '2013',
      link: {
        type: 'generated-index',
        description: "2013 年發布之各種技術文"
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'techPost/2013',
        }
      ],
    },
  ]
};

module.exports = sidebars;
