/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // But you can create a sidebar manually
  techPost: [
    {
      type: 'category',
      label: '2023',
      link: {
        type: 'generated-index',
        description: "2023"
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'techPost/2023',
        }
      ],
    },
    {
      type: 'category',
      label: '2022',
      link: {
        type: 'generated-index',
        description: "2022"
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'techPost/2022',
        }
      ],
    },
    {
      type: 'category',
      label: '2021',
      link: {
        type: 'generated-index',
        description: "2021"
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'techPost/2021',
        }
      ],
    },
    {
      type: 'category',
      label: '2020',
      link: {
        type: 'generated-index',
        description: "2020"
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'techPost/2020',
        }
      ],
    },
    {
      type: 'category',
      label: '2019',
      link: {
        type: 'generated-index',
        description: "2019"
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'techPost/2019',
        }
      ],
    },
    {
      type: 'category',
      label: '2018',
      link: {
        type: 'generated-index',
        description: "2018"
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'techPost/2018',
        }
      ],
    },
  ]
};

module.exports = sidebars;
